# Generated by Django 5.2.16 on 2026-07-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserRegistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('CBC', 'Complete Blood Count'), ('LFT', 'Liver Function Test'), ('KFT', 'Kidney Function Test'), ('LIPID', 'Lipid Profile'), ('SUGAR', 'Blood Sugar Report'), ('HBA1C', 'HbA1c Report'), ('DIABETES', 'Diabetes Panel')], max_length=10)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='blood_reports/')),
                ('extracted_params', models.JSONField(blank=True, default=dict)),
                ('predictions', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_reports', to='UserRegistration.patientsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
