# Generated by Django 5.2.16 on 2026-07-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserRegistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('BRAIN_MRI', 'Brain MRI'), ('CHEST_XRAY', 'Chest X-ray')], max_length=20)),
                ('uploaded_file', models.ImageField(upload_to='medical_images/')),
                ('prediction', models.CharField(blank=True, max_length=200)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('all_class_scores', models.JSONField(blank=True, default=dict)),
                ('model_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_images', to='UserRegistration.patientsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
