# Generated by Django 5.2.16 on 2026-07-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodyScanAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalimage',
            name='image_type',
            field=models.CharField(choices=[('BRAIN_MRI', 'Brain MRI'), ('CHEST_XRAY', 'Chest X-ray'), ('ALZHEIMER', 'Alzheimer MRI')], max_length=20),
        ),
    ]
