# Generated by Django 5.2.16 on 2026-07-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodyScanAnalysis', '0002_alter_medicalimage_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalimage',
            name='image_type',
            field=models.CharField(choices=[('BRAIN_MRI', 'Brain MRI'), ('CHEST_XRAY', 'Chest X-ray'), ('ALZHEIMER', 'Alzheimer MRI'), ('BRAIN_TUMOR_SEGMENTATION', 'Brain Tumor Segmentation')], max_length=30),
        ),
    ]
