# Generated by Django 5.2.16 on 2026-07-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodreport',
            name='report_type',
            field=models.CharField(choices=[('CBC', 'Complete Blood Count'), ('LFT', 'Liver Function Test'), ('KFT', 'Kidney Function Test'), ('LIPID', 'Lipid Profile'), ('SUGAR', 'Blood Sugar Report'), ('HBA1C', 'HbA1c Report'), ('DIABETES', 'Diabetes Panel'), ('COMBINED', 'Combined Reports')], max_length=10),
        ),
    ]
