# Generated by Django 5.1.15 on 2026-07-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodAnalysis', '0002_alter_bloodreport_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodreport',
            name='report_type',
            field=models.CharField(choices=[('CBC', 'Complete Blood Count'), ('LFT', 'Liver Function Test'), ('KFT', 'Kidney Function Test'), ('SUGAR', 'Blood Sugar Report'), ('HBA1C', 'HbA1c Report'), ('COMBINED', 'Combined Reports')], max_length=10),
        ),
    ]
