# Generated by Django 5.2.16 on 2026-07-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsession',
            name='blood_infection',
            field=models.BooleanField(default=False, verbose_name='Recent Blood Infection'),
        ),
        migrations.AddField(
            model_name='patientsession',
            name='diabetes',
            field=models.BooleanField(default=False, verbose_name='History of Diabetes'),
        ),
        migrations.AddField(
            model_name='patientsession',
            name='heart_disease',
            field=models.BooleanField(default=False, verbose_name='Heart Disease'),
        ),
        migrations.AddField(
            model_name='patientsession',
            name='hypertension',
            field=models.BooleanField(default=False, verbose_name='High Blood Pressure'),
        ),
    ]
