# Generated by Django 5.2.16 on 2026-07-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0002_patientsession_blood_infection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsession',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AddField(
            model_name='patientsession',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='patientsession',
            name='smoking_history',
            field=models.CharField(choices=[('Never', 'Never'), ('Former', 'Former'), ('Current', 'Current'), ('Not Current', 'Not Current')], default='Never', max_length=20),
        ),
        migrations.AddField(
            model_name='patientsession',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
