# Generated by Django 5.1.15 on 2026-07-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0003_patientsession_blood_group_patientsession_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsession',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='patientsession',
            name='heart_disease',
        ),
    ]
