# Generated by Django 5.1.15 on 2026-07-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0004_remove_patientsession_diabetes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsession',
            name='smoking_history',
        ),
        migrations.AddField(
            model_name='patientsession',
            name='sugar',
            field=models.IntegerField(choices=[(0, 'No diabetes'), (1, 'Controlled diabetes'), (2, 'Moderately high sugar'), (3, 'High sugar'), (4, 'Very high sugar'), (5, 'Extremely high / uncontrolled')], default=0, verbose_name='Sugar Level (0–5)'),
        ),
    ]
